"""added book_borrower table

Revision ID: 8bfcc0b7b304
Revises: 34898feb1226
Create Date: 2023-09-09 15:32:16.530240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfcc0b7b304'
down_revision = '34898feb1226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_borrowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('borrowed_date', sa.String(), nullable=True),
    sa.Column('borrowed_time', sa.String(), nullable=True),
    sa.Column('return_date', sa.String(), nullable=True),
    sa.Column('return_time', sa.String(), nullable=True),
    sa.Column('borrower_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_borrowers')
    # ### end Alembic commands ###
