"""Added new relationships to the models

Revision ID: 930fadd786a8
Revises: afc9b8478889
Create Date: 2023-09-04 16:41:05.050389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930fadd786a8'
down_revision = 'afc9b8478889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
