"""Added new column to reviews table

Revision ID: adc9a59826a7
Revises: 930fadd786a8
Create Date: 2023-09-04 16:46:27.940156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc9a59826a7'
down_revision = '930fadd786a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
