"""Added the models and implemented relationships

Revision ID: d57b8086cea4
Revises: adc9a59826a7
Create Date: 2023-09-04 17:01:01.991565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57b8086cea4'
down_revision = 'adc9a59826a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
